name: base template

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
      username:
        description: "Username description"
        required: true
  #  secrets:
  #    registry_username:
  #      required: true
  #    registry_password:
  #      required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization

jobs:
  build-step-1:
    runs-on: ubuntu-latest

    steps:      
      - uses: actions/checkout@v2
      
      - name: Set the tag
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
      
      - name: Build and Push the Image
        run: echo "${{inputs.image_name}}:${{env.final_tag}}"
          
  do-something-else-step-2:
    runs-on: ubuntu-latest

    steps:
    - run: echo "Hello ${{inputs.username}}"